### ISSUE TITLE
Stumbled across your work and it's really great

### ISSUE THREAD

**Issue by nicisfurst** [thsconline/thsconline.github.io#1]
Hey Man, I'm a local sydney student and whilst looking for schooling resources, I stumbled across your HSC and Prelim stuff and I've gotta say your repository you've set up is quite impressive. I'm really interested in what you're setting up here and was just hoping I could get in contact with you to inquire more about this thing you're building and if there would be any way I could potentially help (such as getting more recources from my own and contact's schools, or helping with website design), simply because what you're doing I think is really cool and has the potential to turn into something big helping students all across Australia. 

At first glance, I didn't think this project was still updated as the pdf's and other resources unfortunately weren't working, so I followed the github link here to find it thankfully was still being updated and built upon which is really cool. _Just to add to the pdf's not loading, using the beta sign in also didn't work so if there was still some way to access the files that would be much appreciated._

Seeing as I couldn't find any contact info I thought this would be the best way to contacrt you. Please if you do read this I would love to hear back from you either as a reply to this or at my email (listed on account).

Keep up the cool work

**Comment by thsconline** [comment]
Flick an email to thsconline@gmail.com
